swagger: '2.0'
info:
  title: api.gouv.fr
  description: Catalogue des API des administrations françaises
  version: 0.1.0
basePath: /
produces:
  - application/json
paths:
  /api.json:
    get:
      summary: Récupérer la liste des API listées sur api.gouv.fr
      responses:
        '200':
          description: La liste des API
          schema:
            type: array
            items:
              $ref: "#/definitions/api"

definitions:
  api:
    type: object
    properties:
      title:
        type: string
      url:
        type: string
      description:
        type: string
      image:
        type: string
      domain:
        type: string
      owner:
        type: string
      contract:
        type: string
      category:
        type: string
      keywords:
        type: array
        items:
          type: string
      clients:
        type: array
        items:
          type: string
      partners:
        type: array
        items:
          type: string
